config/routes.rb
Rails.application.routes.draw do
 
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  resources :products do
  resources :comments
  end
  devise_for :users
  resources :users 
  resources :orders, only: [:index, :show, :create, :destroy]

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  get 'static_pages/store'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'
  get 'payments/create'

end

app/models/product.rb
class Product < ActiveRecord::Base
	# SHOPPING CART
	has_many :order_items
	default_scope { where(active: true) }
	# SHOPPING CART 


	# PAPERCLIP
	belongs_to :product
	has_attached_file :photo, default_url: "/images/:style/missing.png"
	# PAPERCLIP

	#RATY
	def average_rating
		comments.average(:rating).to_f
	end
	#RATY

	# COMMENTS
	has_many :comments
	# COMMENTS

	#VALIDATION
	validates :name, presence: true
	validates :description, presence: true
	validates :colour, presence: true
	validates :size, presence: true
	validates :price, presence: true
	validates_attachment :photo, presence: true,
	  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
	#VALIDATION

end

app/controllers/products_controller.rb
 class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!,:except => [:show, :index]

# So admin abilities are applied to only these.  
# So public can view product without signing in.
  load_and_authorize_resource :only => [:new, :update, :create, :destroy]

  # ANGULAR
  #respond_to :json, :html

  # GET /products
  # GET /products.json
  def index
  # FOR SEARCH FORM TO USE LIKE IN DEVELOPMENT
      if Rails.env.development?
        if params[:q]
          search_term = params[:q]
          @products = Product.where("name LIKE ?", "%#{search_term}%")
          
          # ANGULAR
          #respond_with @products
          
        else
          @products = Product.all
# SHOPPING CART
    @order_item = current_order.order_items.new
# SHOPPING CART      
        end
      end
  # FOR SEARCH FORM TO USE ILIKE IN PRODUCTION
      if Rails.env.production?
        if params[:q]
          search_term = params[:q]
          @products = Product.where("name ILIKE ?", "%#{search_term}%")
        else
          @products = Product.all
# SHOPPING CART
    @order_item = current_order.order_items.new
# SHOPPING CART          
        end
      end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # GET /products/1
  # GET /products/1.json
  # PAGINATE
  def show
    @comments = @product.comments.order("created_at DESC").paginate(page: params[:page], per_page: 3)
    @product = Product.find(params[:id])
    @order_item = current_order.order_items.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  # PAPERCLIP, added for: "params[:photo]"
  def create
    @product = Product.new(product_params, params[:photo] )
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private


  # Never trust parameters from the scary internet, only allow the white list through.
# PAPERCLIP added :photo
# PRICE added :decimal
  def product_params
    params.require(:product).permit :name, :description, :image_url, :colour, :photo, :photo_file_name, :photo_file_size, :photo_content_type, :photo_updated_at, :price, :decimal, :precision, :scale, :size
  end


end

app/helpers/products_helper.rb
module ProductsHelper



end

app/views/products/_comments.html.erb
<div class="product_reviews">

	<% @comments.each do |comment| %>
		<div class="row">
			<hr>
			<p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>

			<div class="rated" data-score="<%= comment.rating %>"></div>
			<p><%= comment.body %></p>

		<!-- DELETE COMMENT BUTTON -->	
			<p>
				<% if signed_in? && current_user.admin? %>
					<%= link_to 'DELETE COMMENT', product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>
				<% end %>
			</p>
		<!-- DELETE COMMENT BUTTON -->

		</div>
	<% end %>
</div>


app/views/products/_form.html.erb
<div class="store-wrapper">
  <div class="store-inner">

    <%= form_for(@product, :html => {:multipart => true}) do |f| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>


<!-- PAPERCLIP added -->
      <div class="field">
        <%= f.label :photo %><br>
        <%= f.file_field :photo %>
      </div>
<!-- PAPERCLIP added -->


      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description %>
      </div>

      <div class="field">
        <%= f.label :colour %><br>
        <%= f.text_field :colour %><br>   
      </div>

      <div class="field">
        <%= f.label :size %><br>
        <%= f.text_field :size %><br>   
      </div>  

<!-- PRICE -->
      <div class="field">
        <%= f.label :price %><br>
        <%= f.text_field :price %><br> 
      </div>
<!-- PRICE --> 


      <div class="actions">
        <%= f.submit %>
      </div> 
    <% end %>

  </div><!-- end store inner -->
</div><!-- end store wrapper -->

app/views/products/_product.html.erb
<div class="product-index col-lg-4">
	<a href="/products/<%= product.id %>" target="_blank"><h2><%= product.name %></h2></a>
	<a href="/products/<%= product.id %>" target="_blank"><%= image_tag (product.photo), :style => "margin: auto", :class => "img-responsive" %></a>
	<a href="/products/<%= product.id %>" target="_blank"><p><%= product.description %></p></a>
	<p>COLOR:<%= product.colour %></p>
	<p>SIZE:<%= product.size %></p>
	<% if signed_in? && current_user.admin? %>
		<%= link_to 'Show', product %>
		<%= link_to 'Edit', edit_product_path(product) %>
		<%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
</div>

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div>

      <%= form_for order_item, remote: true do |f| %>
        <h4 style="font-family: 'Share Tech Mono', sans-serif;">The Small Price to Pay: 
          <span style="color: green">
            <%= number_to_currency product.price %>
          </span>
        
        </h4>

        <div class="input-group">

          <div class="input-group-btn, add-to-cart-button">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.hidden_field :product_size, value: product.size %>
            <%= f.submit "ADD IT", class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>

    </div>
  </div>
  
</div>

app/views/products/edit.html.erb
<div class="store-wrapper">
	<div class="store-inner">

	<h1>Editing product</h1>

	<!-- PAPERCLIP -->
	<%= form_for @product, url: products_path, html: { multipart: true } do |form| %>
	<% end %>
	<!-- PAPERCLIP -->

	<%= render 'form' %>

	<%= link_to 'Show', @product %> |
	<%= link_to 'Back', products_path %>

	</div><!-- end store inner -->
</div><!-- end store wrapper -->

app/views/products/index.html.erb
<div class="store-wrapper">
  <div class="store-inner">
    
    <div class="store-title visible-lg-block visible-md-block">
      <h1>SLAVE UNIT APPAREL</h1>
        <div class="new-product-button">
          <% if current_user.try(:admin?) %>
            <%= link_to 'New Product', new_product_path, :class => 'btn btn-danger' %>
          <% end %>
        </div>
      <h2>PRODUCT INDEX</h2>
      <h3>Available Late 2016</h3>

<!-- "Items in cart" SHOPPING CART -->
    <h3 class="cart-text">
      <%= render 'layouts/cart_text' %>
    </h3>
<!-- "Items in cart" SHOPPING CART -->    
      
            <% @products.each do |product| %>

<!-- redirect to _product in views -->
                <%= render product %>
<!-- redirect to _product in views -->

            <% end %>
        
    </div><!-- end store-title -->
  </div>
</div>

app/views/products/new.html.erb
<div class="store-wrapper">
	<div class="store-inner">

	<h1>New product</h1>

	<!-- PAPERCLIP -->
	<%= form_for @product, url: products_path, html: { multipart: true } do |form| %>
	<% end %>
	<!-- PAPERCLIP -->

	<%= render 'form' %>

	<%= link_to 'Back', products_path %>

	</div><!-- end store inner -->
</div><!-- end store wrapper -->

app/views/products/show.html.erb
<div class="store-indivproduct">
	<div class="store-indivproductinner">

		<div class="store-indivproduct-notice">
			<h1 id="notice"><%= notice %></h1>
		</div>

		<div class="store-indivproduct-name"=>
		  <h1><%= @product.name %></h1>
		</div>



<!-- DISPLAYS PRODUCT-->
	<!-- PAPERCLIP -->
		<div>
			<h2>How it looks like:</h2>
		</div>
		<div class="store-indivproduct-photo">

	<!-- ELEVATEZOOM added, id, data_zoom_image and script -->
			<%= image_tag @product.photo.url, :class => "img-responsive img-zoom", :data_zoom_image => "@product.photo.url" %>
			<script>
				$(document).on('ready page:load', function () {// document ready
					$(".img-zoom").elevateZoom({scrollZoom : true});
				});//end document ready
			</script>
	<!-- ELEVATEZOOM added, id, data_zoom_image and script -->
	
		</div>
	<!-- PAPERCLIP -->


		<div class="store-indivproduct-desc">
		  <p><%= @product.description %></p>
		  <h3>Available Late 2016</h3>
		</div>	

		<div>
		  <h2>Colour:</strong></h2>
		</div>

		<div class="store-indivproduct-color">
			<p><%= @product.colour %></p>
		</div>

		<div>
		  <h2>Size:</strong></h2>
		</div>

		<div class="store-indivproduct-color">
			<p><%= @product.size %></p>
		</div>





<!-- DISPLAYS PRODUCT-->

<!-- ADD TO CART BUTTON -->
    <div class="well">
  		<div class="row">
    		<div>
		      <%= form_for @order_item, remote: true do |f| %>
		        <h4 style="font-family: 'Share Tech Mono', sans-serif;">The Small Price to Pay: 
		          <span style="color: green">
		            <%= number_to_currency @product.price %>
		          </span>
		        
		        </h4>

		        <div class="input-group">
		         
		          <div class="input-group-btn, add-to-cart-button">
		            <%= f.hidden_field :product_id, value: @product.id %>
		            <%= f.hidden_field :product_size, value: @product.size %>
		            <%= f.submit "ADD IT", class: "btn btn-danger" %>
		          </div>
		        </div>
		      <% end %>
		    </div>
		  </div>
		</div>
<!-- ADD TO CART BUTTON -->

<!-- SIZE AND ADD TO CART BUTTONS -->

<!-- RATY average rating -->
			<h2>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div></h2>
<!-- RATY average rating -->

<!-- RATY -->
		<%= render 'comments' %>
<!-- RATY -->





<!-- COMMENTS -->


		<% if signed_in? %>
			<h4>Review this:</h4>
<!-- AJAX added, remote: true -->
			<%= form_for([@product, @product.comments.build], remote: true) do |f| %>
<!-- AJAX added, remote: true -->
				<p>
					<%= f.label :body, "What do you think?" %><br>
					<%= f.text_area :body %>
				</p>

<!-- RATY -->
				<p>Rate it:
					<div class="rating"></div>
				</p>
<!-- RATY -->

				<p>
					<%= f.submit "TRANSMIT", :class => 'btn btn-danger' %>
					
				</p>
			<% end %>
			
		<% end %>



<!-- PAGINATION -->
			<%= will_paginate @comments %>
<!-- PAGINATION -->

<!-- COMMENTS -->

		<div class="store-indivproduct-buttons">
			<% if signed_in? && current_user.admin? %><%= link_to 'Edit', edit_product_path(@product) %>|<% end %>
			<%= link_to 'Back to Product Index', products_path %>
		</div>
	</div>
</div>