config/routes.rb
Rails.application.routes.draw do
 
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  resources :products do
  resources :comments
  end
  devise_for :users
  resources :users 
  resources :orders, only: [:index, :show, :create, :destroy]

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  get 'static_pages/store'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#landing_page'

  post 'static_pages/thank_you'

  post 'payments/create'
  get 'payments/create'

end

app/views/layouts/_cart_text.html.erb
<%= link_to "The price to pay for all #{current_order.order_items.size} item/s in Cart: #{number_to_currency current_order.subtotal} ", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slave Unit Apparel</title>

  	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
  	<link href='https://fonts.googleapis.com/css?family=Michroma' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Share+Tech+Mono' rel='stylesheet' type='text/css'>

    	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
  	<!-- To use Javascript from the internet -->
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  	<!-- To make responsive on smartphones -->
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<%=csrf_meta_tags %>

  </head>
  <body>
  <!-- NAVBAR and FOOTER-->
  <!-- NAVBAR -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" id="nav">
          <div class="navhome" id="navhome">
              <a href="/" alt="logo"><%= image_tag("logo-nav2.jpg") %></a>
          </div>
          <div class="container-fluid menu">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="/products"><span class="glyphicon glyphicon-eye-open"></a></li>
                <li><a href="/static_pages/about"><span class="glyphicon glyphicon-info-sign"></a></li>
                <li><a href="/static_pages/contact"><span class="glyphicon glyphicon-phone-alt"></a></li>
                <li><a href="/cart"><span class="glyphicon glyphicon-shopping-cart"></a></li>


<!-- SEARCH BOX -->
                <li>
                <%= form_tag("/products", method: "get") do %>
                  <%= text_field_tag(:q) %>
                  <%= submit_tag("SEARCH") %>
                <% end %>
                </li>
<!-- SEARCH BOX -->






<!-- USER Icon -->
                <li>
                  <% if user_signed_in? %>
                    <%= link_to current_user do %>
                      <i class="glyphicon glyphicon-user"></i>
                    <% end %>
                  <% end %>
                </li>
<!-- USER Icon -->

              </ul>





<!-- DEVISE gem login out -->
              <ul class="nav pull-right">
                <li style="padding-top:7px;">
                  <% if user_signed_in? %>
                    <%= link_to('', destroy_user_session_path, :class => "glyphicon glyphicon-log-out", :method => :delete) %>

                  
    
                    <% else %>
                    <%= link_to('', new_user_session_path, :class => "glyphicon glyphicon-log-in") %>
                  <% end %>
                </li>
              </ul>
<!-- DEVISE gem login out -->





            </div>
          </div><!-- end container-fluid menu --> 
  <!-- END NAVBAR -->






  <!-- DEVISE  notice and alert -->
          <% if notice %>
            <div class="alert alert-warning alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= notice %>
            </div>
          <% end %>
          <% if alert %>
            <div class="alert alert-warning alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <strong>ACCESS DENIED.</strong><%= alert %>
            </div>
          <% end %>
  <!-- END DEVISE notice and alert -->






  <!-- FOOTER -->
          <footer class="visible-lg-block visible-md-block" id="footer-lg">
            <div class="fb-like" data-href="https://www.facebook.com/slav3unit" data-layout="button" data-action="like" data-show-faces="true" data-share="true">
            </div><!-- end fb-like -->
            <div class="socialfooter">
              <a href="https://instagram.com/slave_unit" target="_blank"><%= image_tag ("instagram-logo-sm.png") %></a><a href="https://slav3unit.bandcamp.com/releases" target="_blank"><%= image_tag ("bc foot.png") %></a><a href="https://www.flickr.com/photos/gracinhamarco/" target="_blank"><%= image_tag ("flickr foot sm.png") %></a>
            </div><!-- end socialfooter -->
            <div class="footerlogo">
              <div class="footerlogoinside">
                <p>&copy SLAVE UNIT APPAREL 2015</p>
              </div>
            </div><!-- end footerlogo -->
          </footer>
    <!-- mobile footer -->
          <footer class="visible-sm-block visible-xs-block" id="footer-sm">
            <div class="fb-like-sm">
              <div class="fb-like" data-href="https://www.facebook.com/slav3unit" data-layout="button" data-action="like" data-show-faces="true" data-share="true">
              </div>
            </div><!-- end fb-like-sm -->
            <div class="socialfooter-sm">
              <a href="https://instagram.com/slave_unit" target="_blank"><%= image_tag ("instagram-logo-sm.png") %></a><a href="https://slav3unit.bandcamp.com/releases" target="_blank"><%= image_tag ("bc foot.png") %></a><a href="https://www.flickr.com/photos/gracinhamarco/" target="_blank"><a href="https://www.flickr.com/photos/gracinhamarco/" target="_blank"><%= image_tag ("flickr foot sm.png") %></a>
            </div><!-- end socialfooter-sm -->
            <div class="footerlogo-sm">
              <div class="footerlogoinside">
                <p>&copy SLAVE UNIT APPAREL 2015</p>
              </div><!-- end footerlogoinside -->
            </div><!-- end footerlogo-sm -->
    <!-- mobile footer -->
          </footer><!-- end footer visible-sm -->
  <!-- END FOOTER -->
        
      </nav>
  <!-- END NAVBAR and FOOTER-->
     
  <%= yield %>

  </body>

</html>